### ISSUE TITLE
Screenshot in readme.md

### ISSUE THREAD

**Issue by PySimpleGUI** [driverxxvii/PDF_Tools#1]
Include a screenshot in your readme so that visitors to your homepage SEE your project has a GUI (a very very rare thing in Python).

I am going to be posting instructions in the Cookbook and maybe the readme.  I think it's important enough that I made a video about the subject:

https://youtu.be/Uby1O7vHEOA

Please show everyone what you've made.  It increases the chance they'll try it and they will also likely want to look at your code to see how you managed to make a GUI... as I said.... a rare thing in Python.

**Comment by driverxxvii** [comment]
![image](https://user-images.githubusercontent.com/53998160/83416204-3d218a00-a418-11ea-95aa-006509a80c36.png)

Hey Mike, thanks so much for taking a look. That's such a great idea. I'm very new to using github and one of the main reasons I'm starting to is because of your project (with everything being on github). Didn't even realise that you can put images in the readme. Like you say, gui are rare in python so I don't think I've seen one yet!

I've added it to the readme now.

**Comment by PySimpleGUI** [comment]
Ooooooooooooooooo

I LIKE IT!

I gets people's attention right away.

**Comment by PySimpleGUI** [comment]
I don't know if other people use the "trick" I use of using GitHub Issues to store images, but for me, it's worked GREAT.  I don't have to clutter up my GitHub files to store images.  All of my documentation is made using these Issue based screenshots.

Thank you for taking the time to do this.

**Comment by PySimpleGUI** [comment]
By the way, I've not used an INI file before.  I use JSON to store my config settings.  I'm still trying to decide if I want to try using config parser.  JSON save and load are literally 1 line of code and I carry around my settings as a Python dictionary. For ease of coding, I'm not sure that can be beat, but I do want to look at it further.

**Comment by driverxxvii** [comment]
When I did a searched for how to store data JSON and ConfigParser are the two things that showed up. I've never used JavaScript so I thought let's stay away from that.
I've only used ConfigParser very minimally so far so can't really comment much on it.
